services:
  - type: web
    name: owlet-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npx tsx server.ts
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_S3_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
